name: Test

on: [push, pull_request, workflow_dispatch]
jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    # not needed (yet)
    # - uses: cachix/cachix-action@v12
    #   with:
    #     name: hyprland
    #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build
      run: nix build .#hyprcursor-with-tests --print-build-logs --keep-going

      # keep a fixed rev in case anything changes
    - name: Install hyprcursor theme
      run: nix build github:fufexan/dotfiles/4e05e373c1c70a2ae259b2c15eec2ad6e11ce581#bibata-hyprcursor --print-build-logs --keep-going

    - name: Set up env
      run: |
        export HYPRCURSOR_THEME=Bibata-Modern-Classic-Hyprcursor
        export HYPRCURSOR_SIZE=16
        mkdir -p $HOME/.local/share/icons
        ln -s $(realpath result/share/icons/Bibata-Modern-Classic-Hyprcursor) $HOME/.local/share/icons/

    - name: Run test1
      run: nix shell .#hyprcursor-with-tests -c hyprcursor_test1
    - name: Run test2
      run: nix shell .#hyprcursor-with-tests -c hyprcursor_test2
    - name: Run test_c
      run: nix shell .#hyprcursor-with-tests -c hyprcursor_test_c

